const Map<String , String > en={
  'Contunie with phone':'Contunie with phone',
  'Mobile Number':'Mobile Number',
  'Send':'Send',
  'Verify Phone':'Verify Phone',
  'Phone Number Verification':'Phone Number Verification',
  'Enter the code sent to':'Enter the code sent to',
  "Didn't receive the code?":"Didn't receive the code?",
  'RESEND':'RESEND',
  'VERIFY':'VERIFY',
  'User Name':'User Name',
  'Need Help?':'Need Help?',
  'Your Favorite':'Your Favorite',
  'Language switcher':'Language switcher',
  'Change Language':'Change Language',
  'Sms sent':'Sms sent',
  'Sign out':'Sign out',
  'Erorr':'Erorr',
  'fill blank':'fill blank',
  'invalid phone number':'invalid phone number',
  'Wrong code Try again':'Wrong code Try again',
  'Confrim Sign Out':'Confrim Sign Out',
  'Do you really want to sign out ?':'Do you really want to sign out ?',
  'Cancel':'Cancel',
  'Confrim':'Confrim'

};